"""features plan foundation

Revision ID: 010451787642
Revises: 93aa9f967e96
Create Date: 2026-08-29 10:55:53.650715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '010451787642'
down_revision: Union[str, None] = '93aa9f967e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_CYR_TO_LAT_FROM = "АБВЕКМНОРСТУХ"
_CYR_TO_LAT_TO = "ABBEKMHOPCTYX"


def upgrade() -> None:
    # Postgres не позволяет добавлять значения нативного enum внутри той же транзакции,
    # где они могли бы использоваться — выполняем ALTER TYPE в autocommit-блоке
    # (FEATURES-PLAN.md, этап 2: новые причины движения MOVE_OUT/MOVE_IN/WRITE_OFF).
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE movereason ADD VALUE IF NOT EXISTS 'MOVE_OUT'")
        op.execute("ALTER TYPE movereason ADD VALUE IF NOT EXISTS 'MOVE_IN'")
        op.execute("ALTER TYPE movereason ADD VALUE IF NOT EXISTS 'WRITE_OFF'")

    # Код зоны создаётся только латиницей (Scope IN п.1, FEATURES-PLAN.md этап 1.1) —
    # переносим существующие кириллические коды на латинские гомоглифы. Штрихкоды ячеек
    # (cells.barcode) не трогаем — они привязаны к id, не к адресу.
    op.execute(
        f"UPDATE zones SET code = translate(code, '{_CYR_TO_LAT_FROM}', '{_CYR_TO_LAT_TO}') "
        f"WHERE code ~ '[А-ЯЁ]'"
    )
    op.execute(
        f"UPDATE cells SET "
        f"zone_code = translate(zone_code, '{_CYR_TO_LAT_FROM}', '{_CYR_TO_LAT_TO}'), "
        f"address = translate(address, '{_CYR_TO_LAT_FROM}', '{_CYR_TO_LAT_TO}') "
        f"WHERE zone_code ~ '[А-ЯЁ]'"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('comment', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint', 'key', name='uq_idempotency_endpoint_key')
    )
    op.create_index(op.f('ix_idempotency_keys_endpoint'), 'idempotency_keys', ['endpoint'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_key'), 'idempotency_keys', ['key'], unique=False)
    op.add_column('cells', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('uq_cell_address'), 'cells', type_='unique')
    op.drop_constraint(op.f('uq_cell_barcode'), 'cells', type_='unique')
    op.create_index(op.f('ix_cells_deleted_at'), 'cells', ['deleted_at'], unique=False)
    op.create_index('uq_cell_address_live', 'cells', ['address'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_cell_barcode_live', 'cells', ['barcode'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.add_column('products', sa.Column('manual_fields', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('products', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=False)
    op.create_index(op.f('ix_products_archived_at'), 'products', ['archived_at'], unique=False)
    op.create_index('uq_product_barcode_live', 'products', ['barcode'], unique=True, postgresql_where=sa.text('archived_at IS NULL'), sqlite_where=sa.text('archived_at IS NULL'))
    op.add_column('racks', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('uq_rack_zone_number'), 'racks', type_='unique')
    op.create_index(op.f('ix_racks_deleted_at'), 'racks', ['deleted_at'], unique=False)
    op.create_index('uq_rack_zone_number_live', 'racks', ['zone_id', 'number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.add_column('stock_moves', sa.Column('actor', sa.String(length=64), server_default='system', nullable=False))
    op.add_column('stock_moves', sa.Column('comment', sa.String(length=512), nullable=True))
    op.add_column('stock_moves', sa.Column('move_group_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_stock_moves_move_group_id'), 'stock_moves', ['move_group_id'], unique=False)
    # server_default нужен только чтобы ADD COLUMN NOT NULL не упал на уже существующих
    # зонах — заполняем реальный порядок ниже (по алфавиту, как для новых демо-данных)
    # и снимаем дефолт: у новых зон position проставляет сервис явно.
    op.add_column('zones', sa.Column('position', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('zones', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_zones_code'), table_name='zones')
    op.create_index(op.f('ix_zones_code'), 'zones', ['code'], unique=False)
    op.create_index(op.f('ix_zones_deleted_at'), 'zones', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_zones_position'), 'zones', ['position'], unique=False)
    op.create_index('uq_zone_code_live', 'zones', ['code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###

    # Существующие зоны получают позицию по алфавиту — текущий порядок отображения
    # не меняется; новая зона (position по умолчанию сервиса) встаёт после них.
    op.execute(
        "UPDATE zones SET position = sub.rn FROM ("
        "  SELECT id, ROW_NUMBER() OVER (ORDER BY code) AS rn FROM zones"
        ") AS sub WHERE zones.id = sub.id"
    )
    op.alter_column('zones', 'position', server_default=None)


def downgrade() -> None:
    # Кириллизация зон обратно и удаление значений enum не выполняются: Postgres не
    # поддерживает удаление значений из существующего enum, а обратное сопоставление
    # латиница->кириллица для переименованных зон неоднозначно (гомоглиф необратим:
    # 'B' мог быть и 'Б', и 'В'). Откат схемы возможен, откат этих данных — нет.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_zone_code_live', table_name='zones', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_zones_position'), table_name='zones')
    op.drop_index(op.f('ix_zones_deleted_at'), table_name='zones')
    op.drop_index(op.f('ix_zones_code'), table_name='zones')
    op.create_index(op.f('ix_zones_code'), 'zones', ['code'], unique=True)
    op.drop_column('zones', 'deleted_at')
    op.drop_column('zones', 'position')
    op.drop_index(op.f('ix_stock_moves_move_group_id'), table_name='stock_moves')
    op.drop_column('stock_moves', 'move_group_id')
    op.drop_column('stock_moves', 'comment')
    op.drop_column('stock_moves', 'actor')
    op.drop_index('uq_rack_zone_number_live', table_name='racks', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_racks_deleted_at'), table_name='racks')
    op.create_unique_constraint(op.f('uq_rack_zone_number'), 'racks', ['zone_id', 'number'], postgresql_nulls_not_distinct=False)
    op.drop_column('racks', 'deleted_at')
    op.drop_index('uq_product_barcode_live', table_name='products', postgresql_where=sa.text('archived_at IS NULL'), sqlite_where=sa.text('archived_at IS NULL'))
    op.drop_index(op.f('ix_products_archived_at'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.drop_column('products', 'archived_at')
    op.drop_column('products', 'manual_fields')
    op.drop_index('uq_cell_barcode_live', table_name='cells', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uq_cell_address_live', table_name='cells', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_cells_deleted_at'), table_name='cells')
    op.create_unique_constraint(op.f('uq_cell_barcode'), 'cells', ['barcode'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_cell_address'), 'cells', ['address'], postgresql_nulls_not_distinct=False)
    op.drop_column('cells', 'deleted_at')
    op.drop_index(op.f('ix_idempotency_keys_key'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_endpoint'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
