"""receiving: приёмка по плану (Этап 5 плана №3, п.3.1 problems.txt)

receipts получает expected_date/comment/created_by/started_at — карточка приёмки
теперь заводится заранее (клиент, дата, комментарий), а не создаётся неявно первым
сканом. Новая таблица receipt_plan_lines — заявленное количество на товар; принятое
не дублируется отдельным полем, это SUM(receipt_lines.qty) (см.
services.receiving.receipt_progress).

Revision ID: 709c32cd1f0d
Revises: 0a0ecffb8e11
Create Date: 2026-09-15 15:01:08.029358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '709c32cd1f0d'
down_revision: Union[str, None] = '0a0ecffb8e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt_plan_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('expected_qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_id', 'product_id', name='uq_receipt_plan_line_product')
    )
    op.add_column('receipts', sa.Column('expected_date', sa.Date(), nullable=True))
    op.add_column('receipts', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('receipts', sa.Column('created_by', sa.String(length=64), nullable=True))
    op.add_column('receipts', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'started_at')
    op.drop_column('receipts', 'created_by')
    op.drop_column('receipts', 'comment')
    op.drop_column('receipts', 'expected_date')
    op.drop_table('receipt_plan_lines')
    # ### end Alembic commands ###
