"""initial schema

Revision ID: 93aa9f967e96
Revises: 
Create Date: 2026-08-28 20:42:55.873871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '93aa9f967e96'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wb_nm_id', sa.Integer(), nullable=True),
    sa.Column('wb_imt_id', sa.Integer(), nullable=True),
    sa.Column('vendor_code', sa.String(length=128), nullable=True),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('brand', sa.String(length=256), nullable=True),
    sa.Column('size', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.create_index(op.f('ix_products_wb_imt_id'), 'products', ['wb_imt_id'], unique=False)
    op.create_index(op.f('ix_products_wb_nm_id'), 'products', ['wb_nm_id'], unique=True)
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_PROGRESS', 'DONE', name='receiptstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_number'), 'receipts', ['number'], unique=True)
    op.create_index(op.f('ix_receipts_status'), 'receipts', ['status'], unique=False)
    op.create_table('supplies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wb_supply_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'PARTIAL', 'FAILED', 'STALE', name='supplystatus'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qr_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplies_status'), 'supplies', ['status'], unique=False)
    op.create_index(op.f('ix_supplies_wb_supply_id'), 'supplies', ['wb_supply_id'], unique=True)
    op.create_table('wb_api_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_code'), 'zones', ['code'], unique=True)
    op.create_table('fbs_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('wb_warehouse_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='fbstransferstatus'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('wb_response', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fbs_transfers_idempotency_key'), 'fbs_transfers', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_fbs_transfers_product_id'), 'fbs_transfers', ['product_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wb_order_id', sa.String(length=64), nullable=False),
    sa.Column('wb_supply_id', sa.String(length=64), nullable=True),
    sa.Column('supply_id', sa.Integer(), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'CONFIRMED', 'IN_ASSEMBLY', 'PACKED', 'IN_SUPPLY', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'EXPIRED', 'REJECTED_NO_STOCK', name='orderstatus'), nullable=False),
    sa.Column('created_at_wb', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supply_id'], ['supplies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_supply_id'), 'orders', ['supply_id'], unique=False)
    op.create_index(op.f('ix_orders_wb_order_id'), 'orders', ['wb_order_id'], unique=True)
    op.create_index(op.f('ix_orders_wb_supply_id'), 'orders', ['wb_supply_id'], unique=False)
    op.create_table('racks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('cells_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'number', name='uq_rack_zone_number')
    )
    op.create_table('supply_boxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supply_id', sa.Integer(), nullable=False),
    sa.Column('wb_trbx_id', sa.String(length=64), nullable=True),
    sa.Column('sticker_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['supply_id'], ['supplies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rack_id', sa.Integer(), nullable=False),
    sa.Column('zone_code', sa.String(length=2), nullable=False),
    sa.Column('rack_no', sa.Integer(), nullable=False),
    sa.Column('cell_no', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=32), nullable=False),
    sa.Column('barcode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('FREE', 'OCCUPIED', 'BLOCKED', name='cellstatus'), nullable=False),
    sa.Column('blocked_reason', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address', name='uq_cell_address'),
    sa.UniqueConstraint('barcode', name='uq_cell_barcode')
    )
    op.create_index(op.f('ix_cells_address'), 'cells', ['address'], unique=False)
    op.create_index(op.f('ix_cells_barcode'), 'cells', ['barcode'], unique=False)
    op.create_index(op.f('ix_cells_cell_no'), 'cells', ['cell_no'], unique=False)
    op.create_index(op.f('ix_cells_rack_no'), 'cells', ['rack_no'], unique=False)
    op.create_index(op.f('ix_cells_status'), 'cells', ['status'], unique=False)
    op.create_index(op.f('ix_cells_zone_code'), 'cells', ['zone_code'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('picked_qty', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sticker_data', sa.Text(), nullable=True),
    sa.Column('sticker_type', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cell_allowed_barcodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cell_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['cell_id'], ['cells.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cell_id', 'barcode', name='uq_cell_allowed_barcode')
    )
    op.create_index(op.f('ix_cell_allowed_barcodes_barcode'), 'cell_allowed_barcodes', ['barcode'], unique=False)
    op.create_table('order_item_marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('mark_code', sa.Text(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_to_wb_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_marks_mark_code'), 'order_item_marks', ['mark_code'], unique=True)
    op.create_table('pick_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('cell_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('picked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cell_id'], ['cells.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pick_lines_order_id'), 'pick_lines', ['order_id'], unique=False)
    op.create_table('receipt_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('cell_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cell_id'], ['cells.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_by_cell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('cell_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cell_id'], ['cells.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'cell_id', name='uq_stock_product_cell')
    )
    op.create_index(op.f('ix_stock_by_cell_cell_id'), 'stock_by_cell', ['cell_id'], unique=False)
    op.create_index(op.f('ix_stock_by_cell_product_id'), 'stock_by_cell', ['product_id'], unique=False)
    op.create_table('stock_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('cell_id', sa.Integer(), nullable=False),
    sa.Column('qty_delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('RECEIPT', 'PICK', 'ADJUST', name='movereason'), nullable=False),
    sa.Column('ref_type', sa.String(length=32), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cell_id'], ['cells.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_moves_cell_id'), 'stock_moves', ['cell_id'], unique=False)
    op.create_index(op.f('ix_stock_moves_product_id'), 'stock_moves', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_moves_product_id'), table_name='stock_moves')
    op.drop_index(op.f('ix_stock_moves_cell_id'), table_name='stock_moves')
    op.drop_table('stock_moves')
    op.drop_index(op.f('ix_stock_by_cell_product_id'), table_name='stock_by_cell')
    op.drop_index(op.f('ix_stock_by_cell_cell_id'), table_name='stock_by_cell')
    op.drop_table('stock_by_cell')
    op.drop_table('receipt_lines')
    op.drop_index(op.f('ix_pick_lines_order_id'), table_name='pick_lines')
    op.drop_table('pick_lines')
    op.drop_index(op.f('ix_order_item_marks_mark_code'), table_name='order_item_marks')
    op.drop_table('order_item_marks')
    op.drop_index(op.f('ix_cell_allowed_barcodes_barcode'), table_name='cell_allowed_barcodes')
    op.drop_table('cell_allowed_barcodes')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_cells_zone_code'), table_name='cells')
    op.drop_index(op.f('ix_cells_status'), table_name='cells')
    op.drop_index(op.f('ix_cells_rack_no'), table_name='cells')
    op.drop_index(op.f('ix_cells_cell_no'), table_name='cells')
    op.drop_index(op.f('ix_cells_barcode'), table_name='cells')
    op.drop_index(op.f('ix_cells_address'), table_name='cells')
    op.drop_table('cells')
    op.drop_table('supply_boxes')
    op.drop_table('racks')
    op.drop_index(op.f('ix_orders_wb_supply_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_wb_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_supply_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_fbs_transfers_product_id'), table_name='fbs_transfers')
    op.drop_index(op.f('ix_fbs_transfers_idempotency_key'), table_name='fbs_transfers')
    op.drop_table('fbs_transfers')
    op.drop_index(op.f('ix_zones_code'), table_name='zones')
    op.drop_table('zones')
    op.drop_table('wb_api_log')
    op.drop_index(op.f('ix_supplies_wb_supply_id'), table_name='supplies')
    op.drop_index(op.f('ix_supplies_status'), table_name='supplies')
    op.drop_table('supplies')
    op.drop_index(op.f('ix_receipts_status'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_number'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_products_wb_nm_id'), table_name='products')
    op.drop_index(op.f('ix_products_wb_imt_id'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
